apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat
spec:
  type: NodePort  # Change the type to NodePort
  ports:
    - port: 80      # Port on the service
      targetPort: 8080  # Port on the pod
  selector:
    app: tomcat

